In [2]:
import pandas as pd

In [3]:
 chemin = 'C:\\Users\\corvi\\Data\\LOREAL_B2B_order_lines.csv'
df_2 = pd.read_csv(chemin)

In [4]:
df_2

,country,orderId,salonId,orderDateTime,productId,productBasePrice,productQuantity,productTotalPrice
0,Poland,offe5ceb-3956-4ea2-87be-b53eabaecb01,a2f9683b-53fa-417b-9ea9-4f98dae19e9b,2019-04-18 05:20:16,p3300627-302c-4d96-9297-a46202982f6f,3839,1,3839
1,Poland,offe5ceb-3956-4ea2-87be-b53eabaecb01,a2f9683b-53fa-417b-9ea9-4f98dae19e9b,2019-04-18 05:20:16,pe16711e-1a06-4304-9fb7-c1f6f3a50711,270,7,1890
2,Poland,o6b8f4e9-f3a3-4132-9634-f175fedecaf7,a2f9683b-53fa-417b-9ea9-4f98dae19e9b,2023-04-13 20:59:56,pd83555d-9475-469d-926f-5ca33576d3f0,4554,1,4554
3,Poland,o6b8f4e9-f3a3-4132-9634-f175fedecaf7,a2f9683b-53fa-417b-9ea9-4f98dae19e9b,2023-04-13 20:59:56,p6154a42-6470-41f3-bfbc-f1c7d37407b7,1865,1,1865
4,Poland,o6b8f4e9-f3a3-4132-9634-f175fedecaf7,a2f9683b-53fa-417b-9ea9-4f98dae19e9b,2023-04-13 20:59:56,p2cb3fab-61fc-4c7a-ad8f-06140c952705,213,1,213
...,...,...,...,...,...,...,...,...
112516,Germany,o714b08f-f802-4dc9-89ff-5199d17144e4,87995635-f2c1-4de0-a4b0-e154d36121e0,2021-01-21 12:28:08,p209fc00-8c72-4d1c-aad0-dd35e33dcf94,1713,4,6852
112517,Germany,o714b08f-f802-4dc9-89ff-5199d17144e4,87995635-f2c1-4de0-a4b0-e154d36121e0,2021-01-21 12:28:08,p6bf8009-81f5-4f40-9865-23370e897ec5,7,113,791
112518,Germany,o714b08f-f802-4dc9-89ff-5199d17144e4,87995635-f2c1-4de0-a4b0-e154d36121e0,2021-01-21 12:28:08,p006ebad-70a0-45c7-88b0-d9cb8e6e5fbe,318,1,318
112519,Germany,o714b08f-f802-4dc9-89ff-5199d17144e4,87995635-f2c1-4de0-a4b0-e154d36121e0,2021-01-21 12:28:08,p2958b4c-5a55-4e9d-ad64-0149323e4792,235,1,235
112520,Germany,o714b08f-f802-4dc9-89ff-5199d17144e4,87995635-f2c1-4de0-a4b0-e154d36121e0,2021-01-21 12:28:08,pd3e6a87-10bc-4931-b040-f977c98fa65e,90,1,90

In [5]:
df_2.to_csv('order_lines_2.csv', index=False)